apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventapp-deployment
  labels:
    app: eventapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventapp
  template:
    metadata:
      labels:
        app: eventapp
    spec:
      containers:
      - name: eventserver
        image: alachebil/imagetest
        ports:
        - containerPort: 8080
        
---
apiVersion: v1
kind: Service
metadata:
  name: eventapp-service
spec:
  selector:
    app: eventapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31110
